### ISSUE TITLE
Структура проекта не соответствует методичке по кодированию

### ISSUE THREAD

**Issue by d-theus** [mirea-fcyb-2015/ergonometrics#2]
Каталоги `h`, `res`, `src` и пр. должны находиться в корневом каталоге проекта. (Если подразумевали, что это папка `FormObject`, то нет. Проект не располагается в подпапках).

**Comment by BarchDif** [comment]
Исправлено.

**Comment by d-theus** [comment]
Не обязательно, но хорошая практика добавлять к комментариям хэши коммитов.
4b106e7e3
