### ISSUE TITLE
Функция подсчета общего кол-ва эл-ов управления

### ISSUE THREAD

**Issue by BarchDif** [mirea-fcyb-2015/ergonometrics#5]
По ТЗ, до 4.12.15

**Comment by d-theus** [comment]
Какая issue верная? На этой стоит дата 4.12, на другой -- 8.

**Comment by BarchDif** [comment]
Обе верны, Завьялов сказал так сделать.

**Comment by d-theus** [comment]
Тогда из названий не понятно, что это две разных работы. Они же разные?

**Comment by BarchDif** [comment]
Разные.Одна считает ОБЩЕЕ кол-во элементов, вторая- кол-во РАЗНЫХ элементов. Первая говорит: у тебя 50 элементов, вторая: у тебя 20 лейблов и 30 чек боксов. Такое ТЗ...

**Comment by d-theus** [comment]
А, теперь понял. Хорошо, но будьте чуть очевиднее.
Ну, например:
`функция подсчета общего количества элементов управления`

`функция подсчета количества различных элементов управления`

Так просто разницу видно, если названия более менее одинаковы, кроме тех самых ключевых моментов.

**Comment by BarchDif** [comment]
Закрыто, коммит 3c1a9f88
